const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#1A73E8",
    background: "#000000",
    foreground: "#FFFFFF",
    card: "#0F0F0F",
    cardForeground: "#FFFFFF",
    primary: "#1A73E8",
    primaryForeground: "#FFFFFF",
    secondary: "#1C1C1E",
    secondaryForeground: "#FFFFFF",
    muted: "#1C1C1E",
    mutedForeground: "#8E8E93",
    accent: "#1C1C1E",
    accentForeground: "#FFFFFF",
    border: "#2C2C2E",
    input: "#1C1C1E",
    destructive: "#FF3B30",
    destructiveForeground: "#FFFFFF",
    up: "#34C759",
    down: "#FF3B30",
    neutral: "#FFD60A",
    purple: "#8B5CF6",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#1A73E8",
    background: "#000000",
    foreground: "#FFFFFF",
    card: "#0F0F0F",
    cardForeground: "#FFFFFF",
    primary: "#1A73E8",
    primaryForeground: "#FFFFFF",
    secondary: "#1C1C1E",
    secondaryForeground: "#FFFFFF",
    muted: "#1C1C1E",
    mutedForeground: "#8E8E93",
    accent: "#1C1C1E",
    accentForeground: "#FFFFFF",
    border: "#2C2C2E",
    input: "#1C1C1E",
    destructive: "#FF3B30",
    destructiveForeground: "#FFFFFF",
    up: "#34C759",
    down: "#FF3B30",
    neutral: "#FFD60A",
    purple: "#8B5CF6",
  },
  radius: 10,
};

export default colors;
